# PANDAS

### Pandas serisi oluşturma

In [1]:
import pandas as pd 

In [3]:
pd.Series([10,22,43,7,9])

0    10
1    22
2    43
3     7
4     9
dtype: int64

In [4]:
seri = pd.Series([10,22,43,7,9])

In [5]:
type(seri)

pandas.core.series.Series

In [6]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [7]:
seri.dtype

dtype('int64')

In [8]:
seri.size

5

In [9]:
seri.ndim

1

In [10]:
seri.values

array([10, 22, 43,  7,  9])

In [11]:
seri.head

<bound method NDFrame.head of 0    10
1    22
2    43
3     7
4     9
dtype: int64>

In [12]:
seri.head(2)

0    10
1    22
dtype: int64

In [13]:
seri.tail(2)

3    7
4    9
dtype: int64

In [14]:

#İndex isimlendirmesi


In [15]:
pd.Series([99,100,22,45,67], index = [1,3,5,7,9])

1     99
3    100
5     22
7     45
9     67
dtype: int64

In [21]:
seri = pd.Series([99,100,22,45,67], index = ["a","b","c","d","e"])

In [22]:
seri["a":"c"]

a     99
b    100
c     22
dtype: int64

In [23]:
#SÖZLÜK ÜZERİNDEN LİSTE OLUŞTURMA

In [24]:
sozluk = {"reg" : 10 , "log" : 11 ,"cart" : 12}

In [25]:
seri = pd.Series(sozluk)

In [26]:
seri

reg     10
log     11
cart    12
dtype: int64

In [27]:
#iki seriyi birleştirerek seri oluşturma

In [28]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

### Eleman İşlemleri

In [29]:
seri = pd.Series([121,200,150,99] , index = ["reg","loj","cart","rf"])

In [30]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [31]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [32]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [33]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [34]:
seri.values

array([121, 200, 150,  99])

In [36]:
#eleman sorgulama

In [37]:
"reg" in seri

True

In [38]:
"a" in seri

False

In [39]:
seri["reg"]

121

In [40]:
#fancy eleman 

In [41]:
seri[["rf","reg"]]

rf      99
reg    121
dtype: int64

In [43]:
seri["reg"] = 130

In [44]:
seri["reg"]

130

In [46]:
seri["reg" : "loj"]

reg    130
loj    200
dtype: int64

### Pandas DataFrame Oluşturma 

In [ ]:
import pandas as pd 

In [48]:
l = [12,25,63,54,15]

In [51]:
pd.DataFrame(l,columns  = ["degisken_ismi"])

degisken_ismi
0             12
1             25
2             63
3             54
4             15

In [52]:
import numpy as np

In [55]:
m = np.arange(1,26).reshape((5,5))

In [56]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [58]:
pd.DataFrame(m,columns = ["eleman1","eleman2","eleman3","eleman4","eleman5"])

eleman1  eleman2  eleman3  eleman4  eleman5
0        1        2        3        4        5
1        6        7        8        9       10
2       11       12       13       14       15
3       16       17       18       19       20
4       21       22       23       24       25

In [59]:
#df isimlendirme 

In [60]:
df = pd.DataFrame(m,columns = ["eleman1","eleman2","eleman3","eleman4","eleman5"])
df.head()

eleman1  eleman2  eleman3  eleman4  eleman5
0        1        2        3        4        5
1        6        7        8        9       10
2       11       12       13       14       15
3       16       17       18       19       20
4       21       22       23       24       25

In [61]:
df.columns

Index(['eleman1', 'eleman2', 'eleman3', 'eleman4', 'eleman5'], dtype='object')

In [62]:
df.columns = ["a","b","c","d","e"]

In [63]:
df

a   b   c   d   e
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25

In [64]:
type(df)

pandas.core.frame.DataFrame

In [65]:
type(df.columns)

pandas.core.indexes.base.Index

In [66]:
df.axes

[RangeIndex(start=0, stop=5, step=1),
 Index(['a', 'b', 'c', 'd', 'e'], dtype='object')]

In [67]:
df.shape

(5, 5)

In [68]:
df.ndim 

2

In [69]:
df.size

25

In [70]:
df.values

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [71]:
type(df.values)

numpy.ndarray

In [72]:
df.head(2)

a  b  c  d   e
0  1  2  3  4   5
1  6  7  8  9  10

In [74]:
df.tail(3)

a   b   c   d   e
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25

In [75]:
a = np.array([1,2,3,4,5])

In [76]:
pd.DataFrame(a,columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

### Eleman İşlemleri

In [77]:
import numpy as np

In [81]:
s1 = np.random.randint(10,size = 5)
s2 = np.random.randint(10,size = 5)
s3 = np.random.randint(10,size = 5)

In [82]:
sozluk = {"var1" : s1 , "var2" : s2 , "var3" : s3}

In [83]:
sozluk 

{'var1': array([9, 1, 1, 6, 9]),
 'var2': array([9, 8, 0, 8, 5]),
 'var3': array([1, 8, 2, 7, 7])}

In [100]:
df = pd.DataFrame(sozluk)
df

var1  var2  var3
0     9     9     1
1     1     8     8
2     1     0     2
3     6     8     7
4     9     5     7

In [101]:
df[1: 3]

var1  var2  var3
1     1     8     8
2     1     0     2

In [102]:
#silme 

In [103]:
df.drop(0,axis = 0 , inplace = True)  #inplace kalıcı olarak silmeyi sağlar

In [104]:
df

var1  var2  var3
1     1     8     8
2     1     0     2
3     6     8     7
4     9     5     7

In [105]:
#fancy işlemleri ile

In [106]:
l = [1,2]

In [107]:
df.drop(l,axis = 0)

var1  var2  var3
3     6     8     7
4     9     5     7

In [108]:
df

var1  var2  var3
1     1     8     8
2     1     0     2
3     6     8     7
4     9     5     7

In [109]:
#değişkenler için 

In [110]:
"var1" in df

True

In [111]:
L = ["var1","var2","var3"]

In [114]:
for i in L:
    print(i in df)

True
True
True


In [115]:
df["var1"]

1    1
2    1
3    6
4    9
Name: var1, dtype: int64

In [116]:
#değişken ekleme 
df["var4"] = df["var1"] + df["var2"]

In [118]:
df

var1  var2  var3  var4
1     1     8     8     9
2     1     0     2     1
3     6     8     7    14
4     9     5     7    14

In [119]:
#değişken silmek 
df.drop("var3",axis = 1)

var1  var2  var4
1     1     8     9
2     1     0     1
3     6     8    14
4     9     5    14

In [120]:
df

var1  var2  var3  var4
1     1     8     8     9
2     1     0     2     1
3     6     8     7    14
4     9     5     7    14

### Gözlem ve Değişken Seçimi : loc & iloc

In [123]:
import pandas as pd
import numpy as np
m = np.random.randint(1,30 , size = (10,3))
df = pd.DataFrame(m,columns = ["var1","var2","var3"])
df

var1  var2  var3
0    26    28    15
1    16    29    14
2     8    29     2
3    12    26     1
4    17     4     6
5    18    15     4
6    21     3    25
7    19    28    29
8    18    22    15
9    14    23    16

In [126]:
df.loc[0:3]   #3.indexi de alıyor

var1  var2  var3
0    26    28    15
1    16    29    14
2     8    29     2
3    12    26     1

In [127]:
df.iloc[0:3]

var1  var2  var3
0    26    28    15
1    16    29    14
2     8    29     2

In [128]:
df.loc[0:3,"var3"]

0    15
1    14
2     2
3     1
Name: var3, dtype: int64

In [132]:
df.iloc[0:3]["var3"]   #loc ile bir farklılık var.

0    15
1    14
2     2
Name: var3, dtype: int64

In [134]:
df["var1"]

0    26
1    16
2     8
3    12
4    17
5    18
6    21
7    19
8    18
9    14
Name: var1, dtype: int64

In [136]:
df[0:2][["var1","var2"]]

var1  var2
0    26    28
1    16    29

In [137]:
df

var1  var2  var3
0    26    28    15
1    16    29    14
2     8    29     2
3    12    26     1
4    17     4     6
5    18    15     4
6    21     3    25
7    19    28    29
8    18    22    15
9    14    23    16

In [138]:
df.var1

0    26
1    16
2     8
3    12
4    17
5    18
6    21
7    19
8    18
9    14
Name: var1, dtype: int64

In [139]:
df[df.var1 >15]

var1  var2  var3
0    26    28    15
1    16    29    14
4    17     4     6
5    18    15     4
6    21     3    25
7    19    28    29
8    18    22    15

In [140]:
df[(df.var1 > 15)&(df.var3 < 5)]

var1  var2  var3
5    18    15     4

In [141]:
df.loc[(df.var1 > 15),["var1","var2"]]

var1  var2
0    26    28
1    16    29
4    17     4
5    18    15
6    21     3
7    19    28
8    18    22

In [142]:
df[(df.var1 > 15)][["var1","var2"]]

var1  var2
0    26    28
1    16    29
4    17     4
5    18    15
6    21     3
7    19    28
8    18    22

### Birleştime (Join) İşlemleri

In [145]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30,size = (5,3))
df1 = pd.DataFrame(m,columns = ["var1","var2","var3"])
df1

var1  var2  var3
0    23    26     5
1    19    11     8
2     4     4    26
3    14    20    29
4    23    22    11

In [147]:
df2 = df1 + 100
df2

var1  var2  var3
0   123   126   105
1   119   111   108
2   104   104   126
3   114   120   129
4   123   122   111

In [148]:
pd.concat([df1,df2])

var1  var2  var3
0    23    26     5
1    19    11     8
2     4     4    26
3    14    20    29
4    23    22    11
0   123   126   105
1   119   111   108
2   104   104   126
3   114   120   129
4   123   122   111

In [151]:
pd.concat([df1,df2], ignore_index = True)
#ignore_index diyince index düzenlemesi yapar ve karışıklık olmaz.

var1  var2  var3
0    23    26     5
1    19    11     8
2     4     4    26
3    14    20    29
4    23    22    11
5   123   126   105
6   119   111   108
7   104   104   126
8   114   120   129
9   123   122   111

In [153]:
df2.columns = ["var1","var2","deg3"]
df2

var1  var2  deg3
0   123   126   105
1   119   111   108
2   104   104   126
3   114   120   129
4   123   122   111

In [154]:
pd.concat([df1,df2])

var1  var2  var3   deg3
0    23    26   5.0    NaN
1    19    11   8.0    NaN
2     4     4  26.0    NaN
3    14    20  29.0    NaN
4    23    22  11.0    NaN
0   123   126   NaN  105.0
1   119   111   NaN  108.0
2   104   104   NaN  126.0
3   114   120   NaN  129.0
4   123   122   NaN  111.0

bu şekilde hata verir aynı olmayan kategorileri birleştirmek mantıksız olcağından 
kesişimlerini almamızı sağlayan join = "inner" komutunu kullanırız.

In [160]:
pd.concat([df1,df2] ,join = "inner", ignore_index = True)

var1  var2
0    23    26
1    19    11
2     4     4
3    14    20
4    23    22
5   123   126
6   119   111
7   104   104
8   114   120
9   123   122

### İleri Birleştirme İşlemleri

In [161]:
import pandas as pd

In [162]:
#birebir birleştirme

In [167]:
df1= pd.DataFrame({'calisanlar' : ['Ali' , 'Veli','Ayse', 'Fatma'],'grup' : ['Muhasebe','Muhendislik','Muhendislik','insan kaynaklari']})
df1

calisanlar              grup
0        Ali          Muhasebe
1       Veli       Muhendislik
2       Ayse       Muhendislik
3      Fatma  insan kaynaklari

In [169]:
df2= pd.DataFrame({'calisanlar' : ['Ali' , 'Veli','Ayse', 'Fatma'],'ilk giris' : [2010,2009,2014,2019]})
df2

calisanlar  ilk giris
0        Ali       2010
1       Veli       2009
2       Ayse       2014
3      Fatma       2019

In [170]:
pd.merge(df1,df2)

calisanlar              grup  ilk giris
0        Ali          Muhasebe       2010
1       Veli       Muhendislik       2009
2       Ayse       Muhendislik       2014
3      Fatma  insan kaynaklari       2019

In [177]:
pd.merge(df1,df2,on = "calisanlar")

calisanlar              grup  ilk giris
0        Ali          Muhasebe       2010
1       Veli       Muhendislik       2009
2       Ayse       Muhendislik       2014
3      Fatma  insan kaynaklari       2019

In [ ]:
#çoktan teke

In [179]:
df3 = pd.merge(df1,df2)
df3

calisanlar              grup  ilk giris
0        Ali          Muhasebe       2010
1       Veli       Muhendislik       2009
2       Ayse       Muhendislik       2014
3      Fatma  insan kaynaklari       2019

In [181]:
df4 = pd.DataFrame({'grup' : ['Muhasebe','Muhendislik' , 'insan kaynaklari'] ,'mudur' : ['Caner', 'Mustafa', 'Berkcan']})

In [182]:
df4

grup    mudur
0          Muhasebe    Caner
1       Muhendislik  Mustafa
2  insan kaynaklari  Berkcan

In [184]:
pd.merge(df3,df4)

calisanlar              grup  ilk giris    mudur
0        Ali          Muhasebe       2010    Caner
1       Veli       Muhendislik       2009  Mustafa
2       Ayse       Muhendislik       2014  Mustafa
3      Fatma  insan kaynaklari       2019  Berkcan

In [185]:
df5 = pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe',
                              'Muhendislik', 'Muhendislik', 'İK', 'İK'],
                    'yetenekler': ['matematik', 'excel', 'kodlama', 'linux',
                               'excel', 'yonetim']})

df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [186]:
pd.merge(df1,df5)

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux

# Toplulaştırma ve Gruplama(Aggregation & Grouping)
Basit toplulaştırma fonksiyonları:

* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

In [212]:
import seaborn as sns

In [215]:
import pandas as pd

In [216]:
import numpy as np

In [208]:
?sns.load_dataset

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load an example dataset from the online repository (requires internet).

This function provides quick access to a small number of example datasets
that are useful for documenting seaborn or generating reproducible examples
for bug reports. It is not necessary for normal usage.

Note that some of the datasets have a small amount of preprocessing applied
to define a proper ordering for categorical variables.

Use :func:`get_dataset_names` to see a list of available datasets.

Parameters
----------
name : str
    Name of the dataset (``{name}.csv`` on
    https://github.com/mwaskom/seaborn-data).
cache : boolean, optional
    If True, try to load from the local cache first, and save to the cache
    if a download is required.
data_home : string, optional
    The directory in which to cache data; see :func:`get_data_home`.
kws : keys and values, optional
    Additional keyword arguments are passed to passed thr

In [221]:
df = sns.load_dataset("planets")
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [210]:
df.shape  #1035 satır ve 6 değişken 

(1035, 6)

In [218]:
df.mean

<bound method NDFrame._add_numeric_operations.<locals>.mean of                method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]>

In [236]:
df["mass"].mean()  #ortalama hesabı 

2.6381605847953216

In [237]:
df["mass"].count() #mass içindeki değerleri saymak için kullanılır.

513

In [240]:
df["mass"].sum()  #mass içindeki değerlerin toplamı 

1353.37638

In [241]:
df["mass"].min() #mass içindeki minimum değeri bulur.

0.0036

In [242]:
df["mass"].max() #mass içindeki max değeri bulur.

25.0

In [243]:
df["mass"].std() #standart sapmasını hesaplar değerlerin

3.8186166509616046

In [244]:
df["mass"].var() #varyansını hesaplar.

14.58183312700122

In [245]:
df.describe().T #veri setindeki betimsel istatistik olarak yazar.
#buradaki .T transpozunu almamıza yarar.

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [246]:
df.dropna().describe().T  #dropna demek verisetinde eksik gözlemler varsa onları siler.

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0