# PANDAS

### Pandas serisi oluşturma

In [1]:
import pandas as pd 

In [3]:
pd.Series([10,22,43,7,9])

0    10
1    22
2    43
3     7
4     9
dtype: int64

In [4]:
seri = pd.Series([10,22,43,7,9])

In [5]:
type(seri)

pandas.core.series.Series

In [6]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [7]:
seri.dtype

dtype('int64')

In [8]:
seri.size

5

In [9]:
seri.ndim

1

In [10]:
seri.values

array([10, 22, 43,  7,  9])

In [11]:
seri.head

<bound method NDFrame.head of 0    10
1    22
2    43
3     7
4     9
dtype: int64>

In [12]:
seri.head(2)

0    10
1    22
dtype: int64

In [13]:
seri.tail(2)

3    7
4    9
dtype: int64

In [14]:

#İndex isimlendirmesi


In [15]:
pd.Series([99,100,22,45,67], index = [1,3,5,7,9])

1     99
3    100
5     22
7     45
9     67
dtype: int64

In [21]:
seri = pd.Series([99,100,22,45,67], index = ["a","b","c","d","e"])

In [22]:
seri["a":"c"]

a     99
b    100
c     22
dtype: int64

In [23]:
#SÖZLÜK ÜZERİNDEN LİSTE OLUŞTURMA

In [24]:
sozluk = {"reg" : 10 , "log" : 11 ,"cart" : 12}

In [25]:
seri = pd.Series(sozluk)

In [26]:
seri

reg     10
log     11
cart    12
dtype: int64

In [27]:
#iki seriyi birleştirerek seri oluşturma

In [28]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

### Eleman İşlemleri

In [29]:
seri = pd.Series([121,200,150,99] , index = ["reg","loj","cart","rf"])

In [30]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [31]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [32]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [33]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [34]:
seri.values

array([121, 200, 150,  99])

In [36]:
#eleman sorgulama

In [37]:
"reg" in seri

True

In [38]:
"a" in seri

False

In [39]:
seri["reg"]

121

In [40]:
#fancy eleman 

In [41]:
seri[["rf","reg"]]

rf      99
reg    121
dtype: int64

In [43]:
seri["reg"] = 130

In [44]:
seri["reg"]

130

In [46]:
seri["reg" : "loj"]

reg    130
loj    200
dtype: int64

### Pandas DataFrame Oluşturma 

In [ ]:
import pandas as pd 

In [48]:
l = [12,25,63,54,15]

In [51]:
pd.DataFrame(l,columns  = ["degisken_ismi"])

degisken_ismi
0             12
1             25
2             63
3             54
4             15

In [52]:
import numpy as np

In [55]:
m = np.arange(1,26).reshape((5,5))

In [56]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [58]:
pd.DataFrame(m,columns = ["eleman1","eleman2","eleman3","eleman4","eleman5"])

eleman1  eleman2  eleman3  eleman4  eleman5
0        1        2        3        4        5
1        6        7        8        9       10
2       11       12       13       14       15
3       16       17       18       19       20
4       21       22       23       24       25

In [59]:
#df isimlendirme 

In [60]:
df = pd.DataFrame(m,columns = ["eleman1","eleman2","eleman3","eleman4","eleman5"])
df.head()

eleman1  eleman2  eleman3  eleman4  eleman5
0        1        2        3        4        5
1        6        7        8        9       10
2       11       12       13       14       15
3       16       17       18       19       20
4       21       22       23       24       25

In [61]:
df.columns

Index(['eleman1', 'eleman2', 'eleman3', 'eleman4', 'eleman5'], dtype='object')

In [62]:
df.columns = ["a","b","c","d","e"]

In [63]:
df

a   b   c   d   e
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25

In [64]:
type(df)

pandas.core.frame.DataFrame

In [65]:
type(df.columns)

pandas.core.indexes.base.Index

In [66]:
df.axes

[RangeIndex(start=0, stop=5, step=1),
 Index(['a', 'b', 'c', 'd', 'e'], dtype='object')]

In [67]:
df.shape

(5, 5)

In [68]:
df.ndim 

2

In [69]:
df.size

25

In [70]:
df.values

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [71]:
type(df.values)

numpy.ndarray

In [72]:
df.head(2)

a  b  c  d   e
0  1  2  3  4   5
1  6  7  8  9  10

In [74]:
df.tail(3)

a   b   c   d   e
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25

In [75]:
a = np.array([1,2,3,4,5])

In [76]:
pd.DataFrame(a,columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

### Eleman İşlemleri

In [77]:
import numpy as np

In [81]:
s1 = np.random.randint(10,size = 5)
s2 = np.random.randint(10,size = 5)
s3 = np.random.randint(10,size = 5)

In [82]:
sozluk = {"var1" : s1 , "var2" : s2 , "var3" : s3}

In [83]:
sozluk 

{'var1': array([9, 1, 1, 6, 9]),
 'var2': array([9, 8, 0, 8, 5]),
 'var3': array([1, 8, 2, 7, 7])}

In [100]:
df = pd.DataFrame(sozluk)
df

var1  var2  var3
0     9     9     1
1     1     8     8
2     1     0     2
3     6     8     7
4     9     5     7

In [101]:
df[1: 3]

var1  var2  var3
1     1     8     8
2     1     0     2

In [102]:
#silme 

In [103]:
df.drop(0,axis = 0 , inplace = True)  #inplace kalıcı olarak silmeyi sağlar

In [104]:
df

var1  var2  var3
1     1     8     8
2     1     0     2
3     6     8     7
4     9     5     7

In [105]:
#fancy işlemleri ile

In [106]:
l = [1,2]

In [107]:
df.drop(l,axis = 0)

var1  var2  var3
3     6     8     7
4     9     5     7

In [108]:
df

var1  var2  var3
1     1     8     8
2     1     0     2
3     6     8     7
4     9     5     7

In [109]:
#değişkenler için 

In [110]:
"var1" in df

True

In [111]:
L = ["var1","var2","var3"]

In [114]:
for i in L:
    print(i in df)

True
True
True


In [115]:
df["var1"]

1    1
2    1
3    6
4    9
Name: var1, dtype: int64

In [116]:
#değişken ekleme 
df["var4"] = df["var1"] + df["var2"]

In [118]:
df

var1  var2  var3  var4
1     1     8     8     9
2     1     0     2     1
3     6     8     7    14
4     9     5     7    14

In [119]:
#değişken silmek 
df.drop("var3",axis = 1)

var1  var2  var4
1     1     8     9
2     1     0     1
3     6     8    14
4     9     5    14

In [120]:
df

var1  var2  var3  var4
1     1     8     8     9
2     1     0     2     1
3     6     8     7    14
4     9     5     7    14

### Gözlem ve Değişken Seçimi : loc & iloc

In [123]:
import pandas as pd
import numpy as np
m = np.random.randint(1,30 , size = (10,3))
df = pd.DataFrame(m,columns = ["var1","var2","var3"])
df

var1  var2  var3
0    26    28    15
1    16    29    14
2     8    29     2
3    12    26     1
4    17     4     6
5    18    15     4
6    21     3    25
7    19    28    29
8    18    22    15
9    14    23    16

In [126]:
df.loc[0:3]   #3.indexi de alıyor

var1  var2  var3
0    26    28    15
1    16    29    14
2     8    29     2
3    12    26     1

In [127]:
df.iloc[0:3]

var1  var2  var3
0    26    28    15
1    16    29    14
2     8    29     2

In [128]:
df.loc[0:3,"var3"]

0    15
1    14
2     2
3     1
Name: var3, dtype: int64

In [132]:
df.iloc[0:3]["var3"]   #loc ile bir farklılık var.

0    15
1    14
2     2
Name: var3, dtype: int64

In [134]:
df["var1"]

0    26
1    16
2     8
3    12
4    17
5    18
6    21
7    19
8    18
9    14
Name: var1, dtype: int64

In [136]:
df[0:2][["var1","var2"]]

var1  var2
0    26    28
1    16    29

In [137]:
df

var1  var2  var3
0    26    28    15
1    16    29    14
2     8    29     2
3    12    26     1
4    17     4     6
5    18    15     4
6    21     3    25
7    19    28    29
8    18    22    15
9    14    23    16

In [138]:
df.var1

0    26
1    16
2     8
3    12
4    17
5    18
6    21
7    19
8    18
9    14
Name: var1, dtype: int64

In [139]:
df[df.var1 >15]

var1  var2  var3
0    26    28    15
1    16    29    14
4    17     4     6
5    18    15     4
6    21     3    25
7    19    28    29
8    18    22    15

In [140]:
df[(df.var1 > 15)&(df.var3 < 5)]

var1  var2  var3
5    18    15     4

In [141]:
df.loc[(df.var1 > 15),["var1","var2"]]

var1  var2
0    26    28
1    16    29
4    17     4
5    18    15
6    21     3
7    19    28
8    18    22

In [142]:
df[(df.var1 > 15)][["var1","var2"]]

var1  var2
0    26    28
1    16    29
4    17     4
5    18    15
6    21     3
7    19    28
8    18    22

### Birleştime (Join) İşlemleri

In [145]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30,size = (5,3))
df1 = pd.DataFrame(m,columns = ["var1","var2","var3"])
df1

var1  var2  var3
0    23    26     5
1    19    11     8
2     4     4    26
3    14    20    29
4    23    22    11

In [147]:
df2 = df1 + 100
df2

var1  var2  var3
0   123   126   105
1   119   111   108
2   104   104   126
3   114   120   129
4   123   122   111

In [148]:
pd.concat([df1,df2])

var1  var2  var3
0    23    26     5
1    19    11     8
2     4     4    26
3    14    20    29
4    23    22    11
0   123   126   105
1   119   111   108
2   104   104   126
3   114   120   129
4   123   122   111

In [151]:
pd.concat([df1,df2], ignore_index = True)
#ignore_index diyince index düzenlemesi yapar ve karışıklık olmaz.

var1  var2  var3
0    23    26     5
1    19    11     8
2     4     4    26
3    14    20    29
4    23    22    11
5   123   126   105
6   119   111   108
7   104   104   126
8   114   120   129
9   123   122   111

In [153]:
df2.columns = ["var1","var2","deg3"]
df2

var1  var2  deg3
0   123   126   105
1   119   111   108
2   104   104   126
3   114   120   129
4   123   122   111

In [154]:
pd.concat([df1,df2])

var1  var2  var3   deg3
0    23    26   5.0    NaN
1    19    11   8.0    NaN
2     4     4  26.0    NaN
3    14    20  29.0    NaN
4    23    22  11.0    NaN
0   123   126   NaN  105.0
1   119   111   NaN  108.0
2   104   104   NaN  126.0
3   114   120   NaN  129.0
4   123   122   NaN  111.0

bu şekilde hata verir aynı olmayan kategorileri birleştirmek mantıksız olcağından 
kesişimlerini almamızı sağlayan join = "inner" komutunu kullanırız.

In [160]:
pd.concat([df1,df2] ,join = "inner", ignore_index = True)

var1  var2
0    23    26
1    19    11
2     4     4
3    14    20
4    23    22
5   123   126
6   119   111
7   104   104
8   114   120
9   123   122