In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
b = np.array([7,8,9,10])

In [4]:
a*b

array([ 7, 16, 27, 40])

Bu işlemde numpy kütüphanesi sayesinde daha iyi bellek yönetimi ile işlemi kolayca yaparız.Sabit bir type da eleman tutar. 

# Numpy array oluşturma

In [7]:
import numpy as np 

In [8]:
a = np.array([2.0 , 4, 5, 7.122414124])

In [9]:
type(a)

numpy.ndarray

In [10]:
a

array([2.        , 4.        , 5.        , 7.12241412])

tüm hepsini bir float gibi tanıdı yani elemanları tek tip olarak tutuyor.

In [11]:
#sıfırdan array oluşturma 

In [13]:
np.zeros(20 , dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((3,3) , dtype = float ) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.full((3,2),4)

array([[4, 4],
       [4, 4],
       [4, 4]])

In [16]:
np.arange(0,31,5)

array([ 0,  5, 10, 15, 20, 25, 30])

In [17]:
np.linspace(0,4,10)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [20]:
np.random.normal(10,4,(3,3))

array([[ 9.05037848,  9.18277278, 13.67821249],
       [ 8.42677811, 10.98612262, 10.88704672],
       [14.86378871, 18.18320877, 16.34503613]])

In [21]:
np.random.randint(0,10,(3,4))

array([[8, 5, 1, 7],
       [0, 8, 3, 6],
       [8, 9, 1, 2]])

# Numpy array özellikleri

* **ndim** : _boyut sayısı_
* shape : boyut bilgisi
* size : toplam eleman sayısı 
* dtype : array veri tipi

In [24]:
import numpy as np

In [26]:
a = np.random.randint(0,10,(3,3))

In [27]:
a.ndim

2

In [28]:
a.shape

(3, 3)

In [29]:
a.size

9

In [31]:
a.dtype

dtype('int64')

## Yeniden Şekillendirme

In [32]:
import numpy as np

In [37]:
a = np.arange(1,10)

In [38]:
a.ndim

1

In [41]:
b = a.reshape((3,3))  #bu şekilde matris haline çevirdik

In [42]:
b.ndim

2

# Array Birleştirme(Concatenation)

In [43]:
import numpy as np

In [46]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])

In [45]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [47]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a = np.random.randint(0,10 , (2,2))

In [53]:
np.concatenate([a,a]) 
#otomatik olarak axis = 0 olarak gelir ve alt alta ekleme yapar.

array([[2, 7],
       [5, 4],
       [2, 7],
       [5, 4]])

In [56]:
np.concatenate([a,a], axis = 1 ) 
#eğer axis = 1 dersek yan yana ekleme yapabilir.

array([[2, 7, 2, 7],
       [5, 4, 5, 4]])

# Array Ayırma (Splitting)

In [58]:
import numpy as np

In [59]:
x = np.array([1,2,3,4,5,6,78,9,7])

In [67]:
np.split(x , [3,4])    
#0.indexten 3 e kadar 1. array
#3.indexten 4.indexe kadar 2. array
#geriye kalan son array olarak ayrılır.

[array([1, 2, 3]), array([4]), array([ 5,  6, 78,  9,  7])]

In [68]:
a,b,c = np.split(x,[3,4])  #a,b,c değerlerine bu şekilde arrayleri atıyor.

In [63]:
a

array([1, 2, 3])

In [64]:
b

array([4])

In [65]:
c

array([ 5,  6, 78,  9,  7])

In [69]:
#İKİ BOYUTLU AYIRMA

In [70]:
m = np.arange(16).reshape([4,4])

In [71]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [72]:
üst,alt = np.vsplit(m,[2])

In [73]:
üst 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [74]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])