In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
b = np.array([7,8,9,10])

In [4]:
a*b

array([ 7, 16, 27, 40])

Bu işlemde numpy kütüphanesi sayesinde daha iyi bellek yönetimi ile işlemi kolayca yaparız.Sabit bir type da eleman tutar. 

# Numpy array oluşturma

In [7]:
import numpy as np 

In [8]:
a = np.array([2.0 , 4, 5, 7.122414124])

In [9]:
type(a)

numpy.ndarray

In [10]:
a

array([2.        , 4.        , 5.        , 7.12241412])

tüm hepsini bir float gibi tanıdı yani elemanları tek tip olarak tutuyor.

In [11]:
#sıfırdan array oluşturma 

In [13]:
np.zeros(20 , dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((3,3) , dtype = float ) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.full((3,2),4)

array([[4, 4],
       [4, 4],
       [4, 4]])

In [16]:
np.arange(0,31,5)

array([ 0,  5, 10, 15, 20, 25, 30])

In [17]:
np.linspace(0,4,10)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [20]:
np.random.normal(10,4,(3,3))

array([[ 9.05037848,  9.18277278, 13.67821249],
       [ 8.42677811, 10.98612262, 10.88704672],
       [14.86378871, 18.18320877, 16.34503613]])

In [21]:
np.random.randint(0,10,(3,4))

array([[8, 5, 1, 7],
       [0, 8, 3, 6],
       [8, 9, 1, 2]])